name = "aiken-lang/nft_giftcard"
version = "0.0.0"
compiler = "v1.1.5"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/nft_giftcard'"

[repository]
user = "aiken-lang"
project = "nft_giftcard"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
